### PR TITLE
Added Certificate Output in README.md

### PR DESCRIPTION
**Pull request by debjit20504**

### CODE REVIEW

**Comment by HeyAnirudh** [comment]
well done @debjit20504  , now instead of adding the link of video try to attach a playable video without redirecting users. and change the heading as Demo (Vedio)

**Comment by debjit20504** [comment]
> well done @debjit20504 , now instead of adding the link of video try to attach a playable video without redirecting users. and change the heading as Demo (Vedio)

Ok, wait I'll do that

**Comment by debjit20504** [comment]
> well done @debjit20504 , now instead of adding the link of video try to attach a playable video without redirecting users. and change the heading as Demo (Vedio)
Screenshot (464)

It's working fine as you can see it is playable video

**Comment by HeyAnirudh** [comment]
alright!! merged!

**Pull request merged**
