### PR TITLE
Added new Certificate Template

### PR DESCRIPTION
**Pull request by GundaSudarrshan**
I have Added New Certificate Template 
Where It Includes a Logo of Any Society or Organization
Title  - Certificate of Participation
Content  - Relevant Content for any Participant in the certifica

### CODE REVIEW

**Comment by GundaSudarrshan** [comment]
I have Added one More Certificate Template into this branch Pls check out and update

**Comment by HeyAnirudh** [comment]
> I have Added one More Certificate Template into this branch Pls check out and update

did you check weather annotation are working on these certificates?

**Comment by GundaSudarrshan** [comment]
No , I Have Just Added the Certificate Template and 2 New Templates to the Repository , I haven't Changed any Code!!

**Comment by GundaSudarrshan** [comment]
Yeah I have Checked it Now , The name is Displaying on the Certificate but not on the Right Position
Should I Change it Now 
image

**Comment by HeyAnirudh** [comment]
> Yeah I have Checked it Now , The name is Displaying on the Certificate but not on the Right Position Should I Change it Now image

Yeah correct the annotation!

**Comment by GundaSudarrshan** [comment]
@HeyAnirudh  I have **changed the Sizes are adjusted to get the desired position** in the certificates 
Have a **Look at the samples** below  in code i have kept the original Image only

image
image



I **think the Issue is resolved Pls check and Update me**

**Comment by HeyAnirudh** [comment]
> @HeyAnirudh I have **changed the Sizes are adjusted to get the desired position** in the certificates Have a **Look at the samples** below in code i have kept the original Image only
> 
> image image
> 
> I **think the Issue is resolved Pls check and Update me**


looks great!! does the same position of text work with other certificates as well?

**Comment by GundaSudarrshan** [comment]
Yes it works fine for all

**Comment by HeyAnirudh** [comment]
> Yes it works fine for all

alright!! ill merge it

**Pull request merged**
