### PR TITLE
Updated README

### PR DESCRIPTION
**Pull request by Soumya-Kushwaha**

### CODE REVIEW

**Comment by HeyAnirudh** [comment]
> _ No description provided. _

image
hey ive said bold it not make it italic , rest all are good make this changes fast so we can merge it

**Comment by HeyAnirudh** [comment]
@Soumya-Kushwaha merged!!

**Comment by Soumya-Kushwaha** [comment]
Please assign issue level tag!

**Comment by Soumya-Kushwaha** [comment]
@HeyAnirudh Since this issue isn't assigned to me, even after my PR being merged, this isn't counted on the leaderboard.

**Comment by HeyAnirudh** [comment]
> @HeyAnirudh Since this issue isn't assigned to me, even after my PR being merged, this isn't counted on the leaderboard.

i didn't get you... is it like your pr wasn't counted on leaderboard?

**Comment by Soumya-Kushwaha** [comment]
Yess!!

**Pull request merged**
