### PR TITLE
added new feature (certificate options) to the code

### PR DESCRIPTION
**Pull request by GundaSudarrshan**
I have **Modified the code** to create new certificate options as per the **Requirement of Issue**
the user can enter the name and 
**then click on any two options that are displayed in form of images below**
image

**Once the user selects and clicks on view certificate button 
he/she can download the her certificate with the selected template.**

image

### CODE REVIEW

**Comment by HeyAnirudh** [comment]
> I have **Modified the code** to create new certificate options as per the **Requirement of Issue** the user can enter the name and **then click on any two options that are displayed in form of images below** image
> 
> **Once the user selects and clicks on view certificate button he/she can download the her certificate with the selected template.**
> 
> image

sure let me check if its working

**Comment by HeyAnirudh** [comment]
> I have **Modified the code** to create new certificate options as per the **Requirement of Issue** the user can enter the name and **then click on any two options that are displayed in form of images below** image
> 
> **Once the user selects and clicks on view certificate button he/she can download the her certificate with the selected template.**
> 
> image

hey! there are few changes required

1.
image
so i need the certificate options only to when i write my name , the certificate comes before it. form a logic like
-> the textspace should not be null , there must be user name 
-> if username is true then show up the certificate. 
a simple if elif would work! 

if any doubt feel free to contact me

**Comment by GundaSudarrshan** [comment]
> > I have **Modified the code** to create new certificate options as per the **Requirement of Issue** the user can enter the name and **then click on any two options that are displayed in form of images below** image
> > **Once the user selects and clicks on view certificate button he/she can download the her certificate with the selected template.**
> > image
> 
> hey! there are few changes required
> 
> 
> image so i need the certificate options only to when i write my name , the certificate comes before it. form a logic like -> the textspace should not be null , there must be user name -> if username is true then show up the certificate. a simple if elif would work!
> 
> if any doubt feel free to contact me

**yeah I have Updated the Required changes**

**Comment by HeyAnirudh** [comment]
@GundaSudarrshan  it works !! well done

**Comment by HeyAnirudh** [comment]
> > > I have **Modified the code** to create new certificate options as per the **Requirement of Issue** the user can enter the name and **then click on any two options that are displayed in form of images below** image
> > > **Once the user selects and clicks on view certificate button he/she can download the her certificate with the selected template.**
> > > image
> > 
> > 
> > hey! there are few changes required
> > image so i need the certificate options only to when i write my name , the certificate comes before it. form a logic like -> the textspace should not be null , there must be user name -> if username is true then show up the certificate. a simple if elif would work!
> > if any doubt feel free to contact me
> 
> **yeah I have Updated the Required changes**
@GundaSudarrshan well done!! it workds

**Pull request merged**
